apiVersion: v1
kind: Namespace
metadata:
   name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: will
  namespace: dev
  labels:
    app: will
spec:
  replicas: 1
  selector:
    matchLabels:
      app: will
  template:
    metadata:
      labels:
        app: will
    spec:
      containers:
        - name: will-playground
          # this is for minikube only, for gke you have to push the docker image to any container registry
          # then use that image like
          # image: docker.io/username/will-gke:latest
          image: wil42/playground:v1
          # only for minikube, for gke remove this line or set any desired policy
          ports:
            - name: http
              containerPort: 8890
          # Environment variables from configMap, before using this create your config map using
          # kubectl create configmap redishost --from-literal=REDIS_HOST=redis --from-literal=REDIS_PORT=6379
          # for using Cloud memorystore change the REDIS_HOST value to your instance ip

---
apiVersion: v1
kind: Service
metadata:
  name: will
  namespace: dev
spec:
  type: NodePort
  selector:
    app: will
  ports:
    - port: 8888
      nodePort: 31590
      targetPort: 8888
      protocol: TCP



